spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bankingservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

jwt:
  secret: your-256-bit-secret
  expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: 8080
